<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <RootNamespace>WootMouseSettingsWpf</RootNamespace>
        <AssemblyName>WootMouseSettings</AssemblyName>
        <ApplicationIcon>..\TheWootMouse\Assests\wootmouse.ico</ApplicationIcon>
        <ApplicationManifest>app.manifest</ApplicationManifest>

        <!-- Self-contained single-file publish -->
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <SelfContained>true</SelfContained>
        <PublishSingleFile>true</PublishSingleFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TheWootMouse\TheWootMouse.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\TheWootMouse\Infrastructure\Wooting\wooting_analog_sdk.dll" Link="wooting_analog_sdk.dll">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
