<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>WootMouseSettingsUI</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TheWootMouse\TheWootMouse.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\TheWootMouse\Infrastructure\Wooting\wooting_analog_sdk.dll" Link="wooting_analog_sdk.dll">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>